Fix confusing `no running event loop` logs (#12008)
## Describe your changes

This improves our bootstrap logic and prevents the confusing
`RuntimeError: no running event loop` message from being displayed on
unrelated errors. In the current state, if `asyncio.run(main())` throws
an uncaught exception, it will always show as:

```
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:
```

since the exception is thrown within the `except RuntimeError` block.
This is confusing since the RuntimeError is expected.

## Testing Plan

- Existing logic should cover this well.

---

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this
project are made under the Apache 2.0 license.