[Conda] Add base58 and enum-compat packages.
When doing a `conda build .`, streamlit fails building due to missing
dependencies that aren't local or in conda-forge.

```
conda.exceptions.ResolvePackageNotFound:
  - base58
  - enum-compat

conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'base58', 'enum-compat'}
```

These files were autogenerated with this command
```
$ conda skeleton pypi base58 enum-compat --recursive
```