Use urllib instead of Tornado for HTTP request in config.py
I'm hoping this fixes the following bug:

  - LOCAL INFO streamlit.config : Error getting Streamlit credentials. Sharing will be disabled. HTTP 599: Timeout during request
  ERROR:asyncio:Future exception was never retrieved
  future: <Future finished exception=StreamClosedError('Stream is closed',)>
  Traceback (most recent call last):
  File "/Users/adrien/.pyenv/versions/streamlit-refactor/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
  yielded = self.gen.throw(*exc_info)
  File "/Users/adrien/.pyenv/versions/streamlit-refactor/lib/python3.6/site-packages/tornado/http1connection.py", line 161, in _read_message
  header_data = yield header_future
  File "/Users/adrien/.pyenv/versions/streamlit-refactor/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
  value = future.result()
  tornado.iostream.StreamClosedError: Stream is closed