mypy: ignore git package entirely
The recent mypy fix for the `git` import (https://github.com/streamlit/streamlit/pull/3819) is causing mypy to fail locally:

```
$ make mypy
./scripts/mypy
lib/streamlit/git_util.py:37:1: error: Skipping analyzing "git": found module but no type hints or library stubs  [import]
                import git
    ^
lib/streamlit/git_util.py:37:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
lib/streamlit/git_util.py:42: error: unused "type: ignore" comment
                self.repo = git.Repo(path, search_parent_directories=True)  # type: ignore[attr-defined]
```

Instead, let's just have mypy ignore the git package altogether. This should work in both CircleCI and local.