fix: Pass bind parameter to internal widget methods
Fixed missing bind parameter in calls from public widget methods
to their internal implementations (_method). This was causing
NameError: name 'bind' is not defined when using bind="query-params".

Affected widgets:
- selectbox
- multiselect
- number_input
- radio
- slider
- checkbox (and toggle)
- text_input
- text_area
- color_picker